//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeCatalog.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeCatalog.Resources.Language.AppLanguage", typeof(AppLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access.
        /// </summary>
        internal static string Attribute_CannotAccess {
            get {
                return ResourceManager.GetString("Attribute_CannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t see.
        /// </summary>
        internal static string Attribute_CannotSee {
            get {
                return ResourceManager.GetString("Attribute_CannotSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t see components.
        /// </summary>
        internal static string Attribute_CannotSeeComponents {
            get {
                return ResourceManager.GetString("Attribute_CannotSeeComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t see description.
        /// </summary>
        internal static string Attribute_CannotSeeDescription {
            get {
                return ResourceManager.GetString("Attribute_CannotSeeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component name.
        /// </summary>
        internal static string Attribute_ComponentName {
            get {
                return ResourceManager.GetString("Attribute_ComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string Attribute_GroupName {
            get {
                return ResourceManager.GetString("Attribute_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Attribute_Quantity {
            get {
                return ResourceManager.GetString("Attribute_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        internal static string Attribute_RecipeName {
            get {
                return ResourceManager.GetString("Attribute_RecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Attribute_UserName {
            get {
                return ResourceManager.GetString("Attribute_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add all Information. Pictures and aliases are optional. Aliases are with , listed..
        /// </summary>
        internal static string Component_InformationText {
            get {
                return ResourceManager.GetString("Component_InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-connection.
        /// </summary>
        internal static string DataConnection {
            get {
                return ResourceManager.GetString("DataConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are following Recipes using this Component. Do you want to remove them all?.
        /// </summary>
        internal static string DeleteWarningComponentsInRecipe {
            get {
                return ResourceManager.GetString("DeleteWarningComponentsInRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demote to User.
        /// </summary>
        internal static string DemoteAdmin {
            get {
                return ResourceManager.GetString("DemoteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neccessary components.
        /// </summary>
        internal static string Detail_NeccessaryComponent {
            get {
                return ResourceManager.GetString("Detail_NeccessaryComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in recipes.
        /// </summary>
        internal static string Detail_UsedInRecipes {
            get {
                return ResourceManager.GetString("Detail_UsedInRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform is currently not supported..
        /// </summary>
        internal static string Exception_PlatformNotSupported {
            get {
                return ResourceManager.GetString("Exception_PlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string Filter_Components {
            get {
                return ResourceManager.GetString("Filter_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string Filter_Recipes {
            get {
                return ResourceManager.GetString("Filter_Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a group name.
        /// </summary>
        internal static string Group_InformationText {
            get {
                return ResourceManager.GetString("Group_InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection.
        /// </summary>
        internal static string Main_CheckingConnection {
            get {
                return ResourceManager.GetString("Main_CheckingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the connection string.
        /// </summary>
        internal static string Main_ConnectionInput {
            get {
                return ResourceManager.GetString("Main_ConnectionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.xxx.xxx.xxx or https:ressource.
        /// </summary>
        internal static string Main_ConnectionInputPlaceholder {
            get {
                return ResourceManager.GetString("Main_ConnectionInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        internal static string Main_EnterUsername {
            get {
                return ResourceManager.GetString("Main_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your recipes.
        /// </summary>
        internal static string Main_FindYourRecipes {
            get {
                return ResourceManager.GetString("Main_FindYourRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Main_PleaseWait {
            get {
                return ResourceManager.GetString("Main_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entries.
        /// </summary>
        internal static string NoEntry {
            get {
                return ResourceManager.GetString("NoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias,Alias.
        /// </summary>
        internal static string Placeholder_Aliases {
            get {
                return ResourceManager.GetString("Placeholder_Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        internal static string Placeholder_Campaign {
            get {
                return ResourceManager.GetString("Placeholder_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Placeholder_Description {
            get {
                return ResourceManager.GetString("Placeholder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Placeholder_Groups {
            get {
                return ResourceManager.GetString("Placeholder_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi selection.
        /// </summary>
        internal static string Placeholder_MultiSelect {
            get {
                return ResourceManager.GetString("Placeholder_MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Placeholder_Name {
            get {
                return ResourceManager.GetString("Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Description.
        /// </summary>
        internal static string Placeholder_SecretDescription {
            get {
                return ResourceManager.GetString("Placeholder_SecretDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to Admin.
        /// </summary>
        internal static string PromoteAdmin {
            get {
                return ResourceManager.GetString("PromoteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add all information. Aliases are optional and are listed with &apos;,&apos;..
        /// </summary>
        internal static string Recipies_InformationText {
            get {
                return ResourceManager.GetString("Recipies_InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select picture....
        /// </summary>
        internal static string Select_Picture {
            get {
                return ResourceManager.GetString("Select_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components : .
        /// </summary>
        internal static string StatisticCountComponentsText {
            get {
                return ResourceManager.GetString("StatisticCountComponentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes : .
        /// </summary>
        internal static string StatisticCountRecipesText {
            get {
                return ResourceManager.GetString("StatisticCountRecipesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        internal static string SV_AddCampaign {
            get {
                return ResourceManager.GetString("SV_AddCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string SV_AddComponent {
            get {
                return ResourceManager.GetString("SV_AddComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string SV_AddGroup {
            get {
                return ResourceManager.GetString("SV_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string SV_AddRecipe {
            get {
                return ResourceManager.GetString("SV_AddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string SV_AddUser {
            get {
                return ResourceManager.GetString("SV_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string TableComponents {
            get {
                return ResourceManager.GetString("TableComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string TableCount {
            get {
                return ResourceManager.GetString("TableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DnD Recipes.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom rights.
        /// </summary>
        internal static string User_CustomRights {
            get {
                return ResourceManager.GetString("User_CustomRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granted access for groups.
        /// </summary>
        internal static string User_GrantedAccessGroups {
            get {
                return ResourceManager.GetString("User_GrantedAccessGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
